{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "remedai-sa" | quote }}
  namespace: {{ .Values.global.namespace | default "remedai" | quote }}
  labels:
    app.kubernetes.io/name: remedai-sa
    app.kubernetes.io/part-of: remedai-platform
  {{- if or .Values.serviceAccount.annotations .Values.gcs.enabled }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
    {{- if and .Values.gcs.enabled .Values.gcs.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: {{ .Values.gcs.gcpServiceAccount | quote }}
    {{- end }}
  {{- end }}
{{- end }}
